Capstone.Web/Models/Park.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Capstone.Web.Models
{
    public class Park
    {
        public string ParkCode { get; set; }
        public string ParkName { get; set; }
        public string State { get; set; }
        public int Acreage { get; set; }
        public int ElevationInFeet { get; set; }
        public double MilesOfTrail { get; set; }
        public int NumberOfCampsites { get; set; }
        public string Climate { get; set; }
        public int YearFounded { get; set; }
        public int AnnualVisitorCount { get; set; }
        public string InspirationalQuote { get; set; }
        public string InspirationalQuoteSource { get; set; }
        public string ParkDescription { get; set; }
        public int EntryFee { get; set; }
        public int NumberOfAnimalSpecies { get; set; }
    }
}

Capstone.Web/Models/Survey.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Capstone.Web.Models
{
    public class Survey
    {
        public int SurveyId { get; set; }
        public string ParkCode { get; set; }
        public string EmailAddress { get; set; }
        public string State { get; set; }
        public string ActivityLevel { get; set; }
        public string ParkName { get; set; }
        public int ParkVotes { get; set; }

    }
}

Capstone.Web/Models/Weather.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Capstone.Web.Models
{
    public class Weather
    {
        public string ParkCode { get; set; }
        public string ParkName { get; set; }
        public int FiveDayForecastValue { get; set; }
        public double LowTempF { get; set; }
        public double HighTempF { get; set; }
        public double LowTempC
        {
            get
            {
                return (((LowTempF - 32)*5)/9);
            }
        }
        public double HighTempC
        {
            get
            {
                return (((HighTempF - 32) * 5) / 9);
            }
        }
        
        public string Forecast { get; set; }
    }
}

Capstone.Web/Controllers/HomeController.cs
using Capstone.Web.DAL;
using Capstone.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Capstone.Web.Controllers
{
    public class HomeController : Controller
    {

        

        private string connectionString;

        public HomeController(string connectionString)
        {
            this.connectionString = connectionString;
        }

        private IParkDAL _dal;

        public HomeController(IParkDAL dal)
        {
            _dal = dal;
        }

        public ActionResult AllParks()
        {
            IList<Park> parkList = _dal.GetAllParks();

            return View("AllParks", parkList);
        }

        public ActionResult ParkDetail(string parkCode)
        {
            if (parkCode.Equals(null))
            {
                return Index();
            }

            var park = _dal.GetPark(parkCode);
            return View("ParkDetail", park);
        }

        // GET: Home
        public ActionResult Index()
        {
            if (Session["isFahrenheit"] == null)
            {
                Session["isFahrenheit"] = "True";
            }

            return View("Index");
        }

        public ActionResult AllParksWeatherList()
        {
            IList<Park> parkList = _dal.GetAllParks();

            if (Session["isFahrenheit"] == null)
            {
                Session["isFahrenheit"] = "True";
            }

            return View("AllParksWeatherList", parkList);
        }

    }
}

Capstone.Web/Controllers/SurveyController.cs
using Capstone.Web.DAL;
using Capstone.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Capstone.Web.Controllers
{
    public class SurveyController : Controller
    {
        

        private ISurveyDAL _dal;
        public SurveyController(ISurveyDAL dal)
        {
            _dal = dal;
        }

        public ActionResult SurveyResult()
        {
            if (Session["isFahrenheit"] == null)
            {
                Session["isFahrenheit"] = "True";
            }

            return View(_dal.GetAllSurveys());
        }

        [HttpPost]
        public ActionResult Survey(Survey newSurvey)
        {
            _dal.SaveNewSurvey(newSurvey);
            return RedirectToAction("SurveyResult");
        }

        public ActionResult Survey()
        {
            if (Session["isFahrenheit"] == null)
            {
                Session["isFahrenheit"] = "True";
            }

            return View();
        }


        

        


    }
}

Capstone.Web/Controllers/WeatherController.cs
using Capstone.Web.DAL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Capstone.Web.Controllers
{
    public class WeatherController : Controller
    {
        private IWeatherDAL _dal;
        public WeatherController(IWeatherDAL dal)
        {
            _dal = dal;
        }

        public ActionResult WeatherDetail(string parkCode)
        {

            var weather = _dal.GetWeather(parkCode);
            return View("WeatherDetail", weather);
        }

        public ActionResult isFahrenheit(string isFahrenheit, string parkCode)
        {
   
            Session["isFahrenheit"] = isFahrenheit;

            var weather = _dal.GetWeather(parkCode);
            return View("WeatherDetail", weather);
        }



    }
}

Capstone.Web/Views/Home/AllParks.cshtml
@{
    ViewBag.Title = "Top 10 List of National Parks";
}

@using Capstone.Web.Models

@model IList<Park>

<head>

    <link href="~/Content/CSS/parklistpage.css" rel="stylesheet" />

</head>

<div class="main">
    <h2>@ViewBag.Title</h2><br />

    @foreach (Park p in Model)
    {
        <div class="row">
            <div class="img">
                <a href=" @Url.Action("ParkDetail", "Home", new { parkCode = p.ParkCode }, null)">
                <img src="/Content/@(p.ParkCode).jpg" />
                </a>
            </div><br />

            <div class="text">
                <table>
                    <tr>
                        <th><a href=" @Url.Action("ParkDetail", "Home", new { parkCode = p.ParkCode }, null)">@p.ParkName</a><br /><br /></th>
                    </tr>
                    <tr>
                        <td><p>@p.ParkDescription</p></td>
                    </tr>
                </table>
            </div>
        </div>
        <br />
    }
   
</div>

Capstone.Web/Views/Home/AllParksWeatherList.cshtml
@{
    ViewBag.Title = "Choose a Park to View the 5-Day Forecast";
}

@using Capstone.Web.Models

@model IList<Park>

<head>

    <link href="~/Content/CSS/allparksweatherlist.css" rel="stylesheet" />

</head>

<div class="main">
    <h2>@ViewBag.Title</h2><br />

    <div class="list-type1">
        <ul>
            @foreach (Park p in Model)
            {
                <li><a href=" @Url.Action("WeatherDetail", "Weather", new { parkCode = p.ParkCode }, null)">@p.ParkName</a></li>
            }
        </ul>
    </div>
</div>

Capstone.Web/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<head>


 
  
    <link href="~/Content/CSS/homepage.css" rel="stylesheet" />


</head>

<div class="jumbotron">
    <h1>Explore Our National Parks</h1>
    
    <p><a href="~/Home/AllParks/" class="btn btn-primary btn-lg">See All Parks &raquo;</a></p>
</div>

<div> </div>

Capstone.Web/Views/Home/ParkDetail.cshtml
@using Capstone.Web.Models

@model Park

<head>

    <link href="~/Content/CSS/parkdetail.css" rel="stylesheet" />

</head>

<div class="main">
    <div class="imgcontainer">
        @{string imagePath = Path.Combine("/Content/", (Model.ParkCode) + ".jpg");}
        <div>
            <a href="@Url.Action("ParkDetail","Home", new { parkCode = Model.ParkCode }, null)">
                <img src="@imagePath" class="img" alt="Picture of Park" />
            </a>
        </div>
    </div>
    <div class="leftbox">
        <h2 class="parkname">@Model.ParkName</h2>
        <br />
        <h4 class="subhead">Quick Stats</h4>
        <p><b>Located In:</b> @Model.State</p>
        <p><b>Founded:</b> @Model.YearFounded</p>
        <p><b>Annual Visitors:</b> @String.Format("{0:n0}", Model.AnnualVisitorCount)</p>
        <p><b>Total Acreage:</b> @String.Format("{0:n0}", Model.Acreage)</p>
        <p><b>Average Elevation:</b> @String.Format("{0:n0}", Model.ElevationInFeet) ft.</p>
        <br />
        <p><b>Daily Entrance Fee:</b> $@Model.EntryFee</p>
    </div>
    <div class="bottom_main">
        <p class="quote">"@Model.InspirationalQuote" - @Model.InspirationalQuoteSource</p><hr />
        <h5><b>Description:</b> <span class="description">@Model.ParkDescription</span></h5>
        <br />

        <div>
            <div class="bottom_left">
                <h4 class="subhead">Camping & Hiking</h4>
                <p><b>Number of Campsites:</b> @Model.NumberOfCampsites</p>
                <p><b>Miles of Trails:</b> @String.Format("{0:n0}", Model.MilesOfTrail)</p>
            </div>
            <div class="bottom_center">
                <a href=" @Url.Action("WeatherDetail", "Weather", new { parkCode = Model.ParkCode }, null)">
                <p style="color:forestgreen"><b>Five-Day Weather Forecast for @Model.ParkName</b></p>
                </a>
            </div>
            <div class="bottom_right">
                <h4 class="subhead">Climate & Ecology</h4>
                <p><b>Climate Zone:</b> @Model.Climate</p>
                <p><b>Number of Animal Species:</b> @Model.NumberOfAnimalSpecies</p>
            </div>
        </div>
    </div>
</div>

Capstone.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <script src="~/Scripts/bootstrap.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Scripts/modernizr-2.8.3.js"></script>
    <script src="~/Scripts/respond.js"></script>
    <script src="~/Scripts/respond.min.js"></script>
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/Site.css" rel="stylesheet" />
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                   
                    <li><img src="~/Content/Weather/geekdsfwrsg.png" style="height:45px;width:auto" /></li>
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Park List", "AllParks", "Home")</li>
                    <li>@Html.ActionLink("Survey", "Survey", "Survey")</li>
                    <li>@Html.ActionLink("Weather Center", "AllParksWeatherList", "Home")</li>

                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        
    </div>

    @RenderSection("scripts", required: false)
</body>
</html>

Capstone.Web/Views/Survey/Survey.cshtml
@using Capstone.Web.Models
@model Survey

<head>

    <link href="~/Content/CSS/surveyhome.css" rel="stylesheet" />

</head>

<div class="main">
    <h1>Favorite Park Survey Submission:</h1>
    <h2>Choose your favorite!!</h2>
    <br />

    <form method="post" action="@Url.Action("Survey","Survey")">
        <table>
            <tr>
                <td class="item">
                    Select a Park:
                </td>
                <td>
                    <select name="ParkCode" required>
                        <option value="">Select</option>
                        <option value="CVNP"> Cuyahoga Valley National Park </option>
                        <option value="ENP"> Everglades National Park </option>
                        <option value="GNP"> Glacier National Park </option>
                        <option value="GCNP"> Grand Canyon National Park </option>
                        <option value="GTNP"> Grand Teton National Park </option>
                        <option value="GSMNP"> Great Smokey Mountain National Park </option>
                        <option value="MRNP"> Mount Rainier National Park </option>
                        <option value="RMNP"> Rocky Mountain National Park </option>
                        <option value="YNP"> Yellowstone National Park </option>
                        <option value="YNP2"> Yosemite National Park </option>

                    </select>
                </td>
            </tr>
            <tr><td><h2></h2></td></tr>
            <tr>
                <td class="item">
                    User Email:
                </td>
                <td>
                    <input type="text" name="EmailAddress" required />
                </td>
            </tr>
            <tr><td><h2></h2></td></tr>
            <tr>
                <td class="item">
                    State of Residence:
                </td>
                <td>
                    <select name="state" required>
                        <option value="">Select</option>
                        <option value="AL">Alabama</option>
                        <option value="AK">Alaska</option>
                        <option value="AZ">Arizona</option>
                        <option value="AR">Arkansas</option>
                        <option value="CA">California</option>
                        <option value="CO">Colorado</option>
                        <option value="CT">Connecticut</option>
                        <option value="DE">Delaware</option>
                        <option value="DC">District Of Columbia</option>
                        <option value="FL">Florida</option>
                        <option value="GA">Georgia</option>
                        <option value="HI">Hawaii</option>
                        <option value="ID">Idaho</option>
                        <option value="IL">Illinois</option>
                        <option value="IN">Indiana</option>
                        <option value="IA">Iowa</option>
                        <option value="KS">Kansas</option>
                        <option value="KY">Kentucky</option>
                        <option value="LA">Louisiana</option>
                        <option value="ME">Maine</option>
                        <option value="MD">Maryland</option>
                        <option value="MA">Massachusetts</option>
                        <option value="MI">Michigan</option>
                        <option value="MN">Minnesota</option>
                        <option value="MS">Mississippi</option>
                        <option value="MO">Missouri</option>
                        <option value="MT">Montana</option>
                        <option value="NE">Nebraska</option>
                        <option value="NV">Nevada</option>
                        <option value="NH">New Hampshire</option>
                        <option value="NJ">New Jersey</option>
                        <option value="NM">New Mexico</option>
                        <option value="NY">New York</option>
                        <option value="NC">North Carolina</option>
                        <option value="ND">North Dakota</option>
                        <option value="OH">Ohio</option>
                        <option value="OK">Oklahoma</option>
                        <option value="OR">Oregon</option>
                        <option value="PA">Pennsylvania</option>
                        <option value="RI">Rhode Island</option>
                        <option value="SC">South Carolina</option>
                        <option value="SD">South Dakota</option>
                        <option value="TN">Tennessee</option>
                        <option value="TX">Texas</option>
                        <option value="UT">Utah</option>
                        <option value="VT">Vermont</option>
                        <option value="VA">Virginia</option>
                        <option value="WA">Washington</option>
                        <option value="WV">West Virginia</option>
                        <option value="WI">Wisconsin</option>
                        <option value="WY">Wyoming</option>
                    </select>
                </td>
            </tr>
            <tr><td><h2></h2></td></tr>
            <tr>
                <td class="item">
                    Your Activity Level:
                </td>
                <td>
                    <select name="activityLevel" required>
                        <option value="">Select</option>
                        <option value="inactive"> Inactive </option>
                        <option value="sedentary"> Sedentary </option>
                        <option value="active"> Active </option>
                        <option value="extremely active"> Extremely Active </option>
                    </select>
                </td>
            </tr>
            <tr><td><h2></h2></td></tr>
            <tr>
                <td class="item">
                    Thank you!
                </td>
                <td>
                    <input type="submit" value="Submit" />
                </td>
            </tr>

        </table>

    </form>
</div>

Capstone.Web/Views/Survey/SurveyResult.cshtml
@using Capstone.Web.Models
@model List<Survey>

<head>

    <link href="~/Content/CSS/surveyresult.css" rel="stylesheet" />

</head>

<div class="box">

    <h2 style="text-align:center"> Thank you for participating in the Favorite Park Survey!!!</h2>
    <h3 style="text-align:center"> The National Parks are listed by popularity according the the survey.</h3>
    <hr />

    @foreach (var survey in Model)
    {
    <div class="post margin">
        <table>
            <tr>
                <td>
                    <a href=" @Url.Action("ParkDetail", "Home", new { parkCode = survey.ParkCode }, null)">
                        <img class="img" src="/Content/@(survey.ParkCode).jpg" />
                    </a>
                </td>
                <td>
                    <h2 style="font-style:italic; padding-left:25px">@survey.ParkName </h2> <h3 style="padding-left:25px">Has received @survey.ParkVotes vote(s)</h3>
                </td>
            </tr>
            <br />
        </table>
    </div>
    
    }
</div>

Capstone.Web/Views/Weather/WeatherDetail.cshtml
@{
    ViewBag.Title = "5-Day Weather Forecast";
}

@using Capstone.Web.Models

@model List<Weather>

<head>

    <link href="~/Content/CSS/weatherdetail.css" rel="stylesheet" />

</head>

<div class="main">
    <h3>@ViewBag.Title</h3><br />

    <form method="post" action="@Url.Action("isFahrenheit","Weather")">
        <select name="isFahrenheit">
            <option value=@Session["isFahrenheit"]> Select Temperature Type </option>
            <option value="True"> Fahrenheit </option>
            <option value="False"> Celsius </option>
        </select>
        <input type="submit" value="Submit" />
        <input type="hidden" name="parkCode" value="@Model[0].ParkCode" />
    </form>

    <h2>@Model[0].ParkName</h2>

    <table style="margin-top: 35px">
        <tr>
            <th style="width:15%">Day of the Week</th>
            <th style="width:10%; text-align:center">High Temperature</th>
            <th style="width:10%; text-align:center">Low Temperature</th>
            <th style="width:10%"></th>
            <th style="width:25%">Weather Forecast</th>
            <th style="width:30%">Advisories</th>
        </tr>

        @foreach (Weather w in Model)
        {
            <tr class="post">
                <td>
                    <h4>@DateTime.Now.AddDays(w.FiveDayForecastValue - 1).DayOfWeek</h4>
                </td>
                <td>
                    @if (Session["isFahrenheit"].ToString() == "True")
                    {
                        <p class="col">@w.HighTempF°F</p>
                    }
                    @if (Session["isFahrenheit"].ToString() == "False")
                    {
                        <p class="col">@Math.Round(w.HighTempC, 0)°C</p>
                    }
                </td>
                <td>
                    @if (Session["isFahrenheit"].ToString() == "True")
                    {
                        <p class="col">@w.LowTempF°F</p>
                    }
                    @if (Session["isFahrenheit"].ToString() == "False")
                    {
                        <p class="col">@Math.Round(w.LowTempC, 0)°C</p>
                    }
                </td>

                <td>
                    @if (w.Forecast == "snow")
                    {
                        <img class="img" src="/Content/Weather/snow2.png" />
                    }
                    @if (w.Forecast == "partly cloudy")
                    {
                        <img class="img" src="/Content/Weather/partlyCloudy2.png" />
                    }
                    @if (w.Forecast == "cloudy")
                    {
                        <img class="img" src="/Content/Weather/cloudy2.png" />
                    }
                    @if (w.Forecast == "rain")
                    {
                        <img class="img" src="/Content/Weather/rain2.png" />
                    }
                    @if (w.Forecast == "thunderstorms")
                    {
                        <img class="img" src="/Content/Weather/thunderstorms2.png" />
                    }
                    @if (w.Forecast == "sunny")
                    {
                        <img class="img" src="/Content/Weather/sunny2.png" />
                    }
                </td>
                <td>
                    <p>The forecast for today is @w.Forecast.</p>
                </td>
                <td>
                    @if (w.Forecast == "snow")
                    {
                        <p> - Remember to pack snowshoes. </p>
                    }
                    @if (w.Forecast == "rain")
                    {
                        <p> - Remember to pack raingear and wear waterproof shoes. </p>
                    }
                    @if (w.Forecast == "thunderstorms")
                    {
                        <p> - Seek shelter! Avoid hiking on exposed ridges. </p>
                    }
                    @if (w.Forecast == "sunny")
                    {
                        <p> - Remember to pack sunblock. </p>
                    }
                    @if (w.HighTempF >= 75)
                    {
                        <p> - Remember to bring an extra gallon of water. </p>
                    }
                    @if ((w.HighTempF - w.LowTempF) > 20)
                    {
                        <p> - Temperatures will fluctuate, wear breathable layers. </p>
                    }
                    @if (w.LowTempF < 20)
                    {
                        <p> - Danger!! Exposure to frigid temperatures can be deadly. </p>
                    }
                </td>
            </tr>
        }
    </table>
</div>